[package]
name = "evaluator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "14"
wasmtime-wasi = "14"
wasi-common = "14"
deterministic-wasi-ctx = "0.1.16"
anyhow = "1"

